spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/book
    username: sa
    password:
    driver-class-name: org.h2.Driver
  servlet:
    multipart:
      enabled: true
      location: /Users/tkHeo/Desktop/upload
      max-request-size: 30MB
      max-file-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
# show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug



